%#######################################################################
%
%                    * READ PHILIPS T1rho Program *
%
%          M-File which reads the T1rho values generated by Philips
%      from the DICOM files.  The T1rho values are scaled and saved to
%      a MAT file.
%
%     NOTES:  1.  The T1rho DICOM files must be in the subdirectory
%             v4\DICOM\.
%
%             2.  The image size is assumed to be 512 pixels.  See
%             variable "npxp" on line 22.
%
%     04-Aug-2020 * Mack Gardner-Morse
%

%#######################################################################
%
% Number of Pixels
%
npxp = 512;             % Number of pixels in each direction (symmetrical)
%
% Get Data Subdirectory and Filenames for the Four Series
%
dir_nam = fullfile('v4','DICOM');
fnamsp = dir(fullfile(dir_nam,'IM_*'));
fnamsp = {fnamsp.name}';
nfiles = size(fnamsp,1);
%
% Get Index to the Series Based on the Numbers in the File Names
%
a = [ ['['; repmat(' ',nfiles-1,1)] char(extractAfter(fnamsp,'_')) ...
    [repmat(';',nfiles-1,1); ']'] ];
a = a';
a = a(:)';
fnums = eval(a);        % Numbers in the filenames
fdif = diff(fnums);
id1p = find(fdif>1);
id1p = [1; id1p+1];     % Index to series
%
% Get Series Descriptions
%
ns = size(id1p,1);
id1p = [id1p; nfiles];
series_descp = cell(ns,1);
for k = 1:ns
   idp = id1p(k);
   info = dicominfo(fullfile(dir_nam,fnamsp{idp}));
   series_descp{k} = info.SeriesDescription;
end
%
% Pick Series and Get Index to Files
%
idxp = menu('Pick a WIP Series',series_descp);
idp = id1p(idxp):id1p(idxp+1)-1;       % Index to filenames
nfp = length(idp);      % Number of files (slices)
%
%  Get Series Description
%
fsp = series_descp{idxp};
fsp = extractAfter(fsp,'3DMAPPS');     % Short series description w/o WIP & 3DMAPPS
fsp = strtrim(fsp);     % Series description
%
% Set Up Array for Loop
%
T1rhop = zeros(npxp,npxp,nfp,'single');     % Philips' time constants
%
% Loop through Files (Slices)
%
for k = 1:nfp
%
   fnam = fnamsp{idp(k)};              % Filename for this slice
   fnam = fullfile(dir_nam,fnam);
%
% Load and Scale Image
%
   img = dicomread(fnam);
   img = single(img);
%
   info = dicominfo(fnam);
   sl = single(info.RescaleSlope);
   offst = single(info.RescaleIntercept);   % Usually zero
   T1rhop(:,:,k) = sl*img+offst;
%
end
%
% Save MAT File
%
mnam = ['T1rhop_' fsp '.mat'];
%
save(mnam,'idp','id1p','idxp','fnamsp','fsp','nfp','npxp','T1rhop', ...
          'series_descp');
%
return